#!/bin/bash

# double click x11
function dcc {
    /usr/bin/env osascript <<-EOF
    tell application "XQuartz"
        reopen
        activate
    end tell

    tell application "System Events" to keystroke "," using {command down}
    tell application "System Events" to keystroke "  "
    tell application "System Events" to keystroke "w" using {command down}

    delay 0.3
    tell application "Terminal"
        reopen
        activate
    end tell
EOF
}

# about VPN connecting
function vpnconnect {
    randomIP4VPN
    /usr/bin/env osascript <<-EOF
    tell application "System Events"
            tell current location of network preferences
                    set VPN to service "VPN (L2TP)"
                    if exists VPN then connect VPN
                    repeat while (current configuration of VPN is not connected)
                        delay 1
                    end repeat
            end tell
    end tell
EOF
}

function vpndisconnect {
    /usr/bin/env osascript <<-EOF
    tell application "System Events"
            tell current location of network preferences
                    set VPN to service "VPN (L2TP)"
                    if exists VPN then disconnect VPN
            end tell
    end tell
    return
EOF
}

function randomIP4VPN {
    vpnfile="vpn.list"
    common="/Users/Hans/.vpnSetting/"
    gshuf ${common}/${vpnfile} | head -1 > ${common}/.listtmp

    ## backup the first version of preference list
    if [ ! -f ${common}/preferences.plist ]; then
        cp /Library/Preferences/SystemConfiguration/preferences.plist ${common}/
    fi

    shuf_vpn_server=`cat ${common}/.listtmp`
    sudo sed -i "213s@g>.\{0,100\}<@g>${shuf_vpn_server}<@" /Library/Preferences/SystemConfiguration/preferences.plist

    rm ${common}/.listtmp
}

# change name for shell tab
function nn {
  if [ -z "$1" ]
  then
    title=${PWD##*/} # current directory
  else
    title=$1 # first param
  fi
  echo -n -e "\033]0;$title\007"
}

# generate a backup
function backup
{
    if [ ! -z "$1" ] && [ "$1" == "-clean" ]; then
        if [ -f ~/.backup.logs ]; then
            rm ~/.backup.logs
        fi
    elif [ ! -z "$1" ] && [ -e "$1" ]; then
        current_time=`date +%Y%m%d`_`date +%T`
        absolute_path=`realpath $1`
        file_name=$(basename "${absolute_path}")
        file_path=$(dirname "${absolute_path}")
        touch "${file_path}/.tmp" > /dev/null
        if [ -f "${file_path}/.tmp" ]; then
            rm "${file_path}/.tmp"
            cp -r $1 "${file_path}/${file_name}_${current_time}"
            chmod a-w "${file_path}/${file_name}_${current_time}"
            if [ -f "$1" ]; then
                md5=$(echo `md5sum $1` | awk '{print $1}')
            else
                md5="Direction"
            fi
            if [ ! -z "$2" ]; then
                exp=`echo $2`
            else
                exp="No explain. "
            fi
            echo -e "${file_name}\t${current_time}\t${file_path}\t${md5}\t${exp}" >> ~/.backup.logs
            backup_file_dir="${file_path}/${file_name}_${current_time}"
            echo "------" >> ~/.backup.logs
            echo -e "${green}[FINISHED]${endcolor} ${file_path}/${file_name}_${current_time}"
        else
            echo -e "${red}[ERROR]${endcolor} permission denied! "
        fi
    else
        echo -e "${red}[ERROR]${endcolor} file not exists! "
    fi
}

# redifine use subl
if [ "$(uname)" == "Darwin" ]; then
    function subl
    {
        /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl $1
    }
fi

# redefine pushd and popd
function pushdd
{
    pushd $1 > /dev/null
}
function popdd
{
    popd > /dev/null
}

# git regenerate origin
function gitregenerate
{
    if [ ! -d .git ]; then
        echo "No git repo found.."
        return
    fi
    if [ ! -f .git/FETCH_HEAD ]; then
        echo "Please fetch or pull first.."
        return
    fi

    if [[ $1 = "-a" ]]; then
        git_rege_name=${2:-"#GITNAME#"}
        git_rege_password=${3:-"#GITPASSWD#"}
    else
        read -p "git name: " git_rege_name
        read -sp "git passwd: " git_rege_password
        echo -ne "\n"
    fi

    repo_web=`awk '{print $NF}' .git/FETCH_HEAD`
    git remote rm origin
    new_web=`echo ${repo_web} | sed "s@https://@https://${git_rege_name}:${git_rege_password}\@@"`
    git remote add origin ${new_web}
}

# sedding
function sedding
{
    while read data; do
        echo "${data}" | sed "s@ @\\\ @g;s@\\\$@\\\\\$@g;s@'@\\\\\'@g;s@\"@\\\\\"@g;s@(@\\\(@g;s@)@\\\)@"
    done
}

# delete enter
function de
{
    while read data; do
        tmp=$(echo -n ${data} | sed "s@\\\$@\\\\\$@g;s@\"@\\\\\"@g")
        echo -n "\"${tmp}\"" | pbcopy
    done
}
