#!/usr/bin/env bash

# ====================CONFIG THIS =============================== #
COLOR_01="#000000"           # HOST
COLOR_02="#C5624C"           # SYNTAX_STRING
COLOR_03="#6DBB63"           # COMMAND
COLOR_04="#EBB17E"           # COMMAND_COLOR2
COLOR_05="#729fcf"           # PATH
COLOR_06="#EE7973"           # SYNTAX_VAR
COLOR_07="#85e0ec"           # PROMP
COLOR_08="#94A3A5"           #

COLOR_09="#979797"           #
COLOR_10="#D32C1F"           # COMMAND_ERROR
COLOR_11="#8ADA7E"           # EXEC
COLOR_12="#EBB17E"           #
COLOR_13="#729fcf"           # FOLDER
COLOR_14="#EE7973"           #
COLOR_15="#85e0ec"           #
COLOR_16="#ffffff"           #

BACKGROUND_COLOR="#282B34"   # Background Color
FOREGROUND_COLOR="#AEBDBE"   # Text
CURSOR_COLOR="$FOREGROUND_COLOR" # Cursor
PROFILE_NAME="Xcode"
# =============================================================== #







# =============================================================== #
# | Apply Colors
# ===============================================================|#
function gogh_colors () {
    echo ""
    echo -e "\e[0;30m█████\\e[0m\e[0;31m█████\\e[0m\e[0;32m█████\\e[0m\e[0;33m█████\\e[0m\e[0;34m█████\\e[0m\e[0;35m█████\\e[0m\e[0;36m█████\\e[0m\e[0;37m█████\\e[0m"
    echo -e "\e[0m\e[1;30m█████\\e[0m\e[1;31m█████\\e[0m\e[1;32m█████\\e[0m\e[1;33m█████\\e[0m\e[1;34m█████\\e[0m\e[1;35m█████\\e[0m\e[1;36m█████\\e[0m\e[1;37m█████\\e[0m"
    echo ""
}

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENT_PATH="$(dirname "$SCRIPT_PATH")"

if [ -e "${PARENT_PATH}/apply-colors.sh" ]
then
gogh_colors
source "$PARENT_PATH/apply-colors.sh"

else
gogh_colors
source <(wget  -O - https://raw.githubusercontent.com/Mayccoll/Gogh/master/apply-colors.sh)
fi
